tunnel: ea1edca9-e52d-4ac8-927d-e43fc7010af4
credentials-file: /etc/cloudflared/ea1edca9-e52d-4ac8-927d-e43fc7010af4.json

ingress:
  # home page
  - hostname: pitrified.qzz.io
    service: http://localhost:8090
  # Catch-all (Required)
  - service: http_status:404

